In [135]:
import pandas as pd
import numpy as np 
from numpy import array

In [136]:
pro = pd.read_csv("C:/Users/asehg/Desktop/Games/FE520Project.csv")

In [137]:
pro

Revenues_prev  COGS_prev  SG&A_prev  R&D_prev  EBIT_prev  EBITDA_prev  \
0            405.50      83.75      13.00      0.00     142.25       270.25   
1            499.00     101.00      19.00      0.00     223.50       377.25   
2            605.50     142.75      19.75      0.00     209.50       402.75   
3            363.00     129.50      18.25      0.00       2.50       184.75   
4               NaN        NaN        NaN       NaN        NaN          NaN   
...             ...        ...        ...       ...        ...          ...   
1150        1112.50     280.00     458.50     59.00     313.75       403.25   
1151        1117.50     280.50     451.50     56.00     328.00       418.25   
1152        1155.25     316.00     437.00     50.25     331.25       420.50   
1153        1167.75     310.00     437.25     46.50     349.50       443.00   
1154        1499.00     449.75     570.75     66.75     326.00       444.00   

      Interest expense, net_prev  Abnormal Gains/Losses_prev  \
0                          11.75                        3.75   
1                          13.25                       -0.50   
2                          17.75                       -1.50   
3                          21.00                     1005.00   
4                            NaN                         NaN   
...                          ...                         ...   
1150                       10.75                       58.00   
1151                       14.00                       66.00   
1152                       13.25                       63.75   
1153                       12.25                       90.25   
1154                       69.00                      209.00   

      Income Taxes_prev  Net Income from Discontinued Op._prev  ...  \
0                 51.00                                    0.0  ...   
1                 81.75                                    0.0  ...   
2                 76.75                                    0.0  ...   
3               -368.50                                    0.0  ...   
4                   NaN                                    NaN  ...   
...                 ...                                    ...  ...   
1150              54.25                                    0.0  ...   
1151              59.00                                    0.0  ...   
1152              57.00                                    0.0  ...   
1153              54.50                                    0.0  ...   
1154               1.25                                    0.0  ...   

      Free Cash Flow_curr  Gross Margin_curr  Operating Margin_curr  \
0                 -126.50           0.796225               0.443250   
1                  -91.50           0.762500               0.343525   
2                  310.50           0.635350               0.004750   
3                   36.75           0.624350               0.158750   
4                     NaN                NaN                    NaN   
...                   ...                ...                    ...   
1150               276.50           0.748375               0.293000   
1151               256.00           0.725250               0.285250   
1152               294.00           0.734025               0.298875   
1153               332.50           0.709350               0.234200   
1154               241.50           0.691033               0.184167   

      Net Profit Margin_curr  Return on Equity_curr  Return on Assets_curr  \
0                   0.278950               0.036875               0.020125   
1                   0.215400               0.030350               0.015825   
2                  -1.823000              -0.198400              -0.105775   
3                  -0.399675              -0.040500              -0.021500   
4                        NaN                    NaN                    NaN   
...                      ...                    ...                    ...   
1150                0.168550        

In [138]:
pro.describe()

Revenues_prev     COGS_prev    SG&A_prev     R&D_prev    EBIT_prev  \
count     984.000000    909.000000   909.000000   909.000000   984.000000   
mean     2545.597222   1656.556656   358.379080    46.562156   313.476711   
std      5299.259673   4610.361920   613.257056   259.451139   465.502225   
min         0.000000      0.000000     0.000000     0.000000 -1259.250000   
25%       470.000000    142.750000    46.750000     0.000000    63.687500   
50%      1131.000000    447.500000   132.500000     0.000000   179.250000   
75%      2413.000000   1283.000000   424.250000     0.000000   373.625000   
max     50103.000000  43192.000000  5600.000000  3070.500000  4840.000000   

       EBITDA_prev  Interest expense, net_prev  Abnormal Gains/Losses_prev  \
count   944.000000                  909.000000                  984.000000   
mean    482.382239                   56.920242                   44.375932   
std     744.866427                   95.841037                  292.128579   
min    -293.000000                  -18.000000                -1285.750000   
25%     110.937500                    8.750000                    0.000000   
50%     278.750000                   25.750000                    0.000000   
75%     549.750000                   65.750000                   16.750000   
max    8886.000000                 1073.000000                 6848.750000   

       Income Taxes_prev  Net Income from Discontinued Op._prev  ...  \
count         984.000000                             984.000000  ...   
mean           54.044631                             -11.267022  ...   
std           335.173416                              83.107809  ...   
min         -8707.750000                           -1328.500000  ...   
25%             2.750000                               0.000000  ...   
50%            25.500000                               0.000000  ...   
75%            77.062500                               0.000000  ...   
max          2052.000000                             430.500000  ...   

       Net Change in Cash_curr  Free Cash Flow_curr  Gross Margin_curr  \
count              1034.000000           960.000000         924.000000   
mean                 16.403046           120.170747           0.495600   
std                 272.153068          1252.006292           0.259552   
min               -2045.000000        -18313.000000          -0.099975   
25%                 -26.250000            18.750000           0.285388   
50%                   1.000000           100.625000           0.474725   
75%                  38.750000           283.250000           0.673519   
max                2582.000000         15486.500000           2.116950   

       Operating Margin_curr  Net Profit Margin_curr  Return on Equity_curr  \
count            1001.000000             1001.000000             948.000000   
mean                0.080489               -0.020950               0.060817   
std                 3.069795                3.479547               0.802820   
min               -96.744050             -109.497025              -1.820367   
25%                 0.082975                0.033700               0.012625   
50%                 0.145375                0.075100               0.025975   
75%                 0.248225                0.154375               0.045463   
max                 3.192650                7.065175              22.777625   

       Return on Assets_curr  Current Ratio_curr  \
count             948.000000          946.000000   
mean                0.009727            1.792106   
std                 0.033503            1.563755   
min                -0.839900           -0.222600   
25%                 0.003688            0.980613   
50%                 0.009487            1.427237   
75%                 0.018063            2.175140   
max                 0.072875           16.888100   

       Liabilities to Equity Ratio_curr  Debt to Assets Ratio_curr  
count                       1023.000000     

In [139]:
def data_cleaning(data, thresh):
    data = data.dropna(axis=0,thresh = thresh)
    data = data.reset_index(drop=True)
    return data

In [140]:
def count_rating(data):
    rating_type = ['AA', 'A', 'BBB', 'BB']
    count_num = [0,0,0,0,0]
    list_a = data['rating'].values.tolist()
    for i in list_a:
        fcnt=0
        for w in range(len(rating_type)):
            if fcnt==0 and rating_type[w] in i:
                count_num[w]=count_num[w]+1
                fcnt=1
            if fcnt==1:
                break
        if fcnt==0:
            count_num[-1]+=1
    return count_num

In [141]:
pro1 = data_cleaning(pro,60)

In [142]:
rating_count = count_rating(pro1)

In [143]:
rating_count

[16, 134, 475, 205, 167]

In [144]:
sum(rating_count)

997

In [145]:
def Y_var(df):
    l = list()
    for e in range(len(df['rating'])):
        if 'AA' in df['rating'].iloc[e]:
            l.append(0)
        elif 'A' in df['rating'].iloc[e]:
            l.append(1)
        elif 'BBB' in df['rating'].iloc[e]:
            l.append(2)
        elif 'BB' in df['rating'].iloc[e]:
            l.append(3)
        else:
            l.append(4)
    return l

In [146]:
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import (GridSearchCV, StratifiedKFold,cross_val_score,
train_test_split)
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from scipy.interpolate import UnivariateSpline, splrep
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import pickle
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix,classification_report

In [151]:
# getting data set with independent varubale 
x_var = pro1.drop('rating',axis=1)
imputer_x_var = SimpleImputer(missing_values=np.nan, strategy='mean')
#X_var_final = imputer_x_var.fit_transform(x_var.values)

In [152]:
y = Y_var(pro1)

In [153]:
def pca_(X_var, n_comp):
    pca = PCA(n_components=n_comp)
    pca.fit(X)
    print("Explained var after PCA = ", sum(pca.explained_variance_ratio_))
    X_var = pca.transform(X)
    return X_var

In [154]:
def knn_model(nf, trh,n_comp=0):
    X = imputer_x_var.fit_transform(x_var.values)
    if n_comp>0:
        X = pca_(X,n_comp)
    scaler = StandardScaler()
    scaler.fit(X)
    x = scaler.transform(X)
    y = Y_var(pro1)
# Split data into training and test set
    x_train, x_dev, y_train, y_dev = train_test_split(x, y, stratify=y,test_size = 0.25, random_state= 20 )
    print('Nearest neighbors')
    n = 2
    knn = KNeighborsClassifier(n_neighbors=n, weights='distance',algorithm='kd_tree', p=1)
    knn.fit(x_train, y_train)
    score = knn.score(x_dev, y_dev)
    preds = knn.predict(x_dev)
    print(type(preds))
    print(type(y_dev))
    print(confusion_matrix(y_dev, preds))
    print("Accuracy = ", score)
    return score

knn_ = knn_model(41,85)

Nearest neighbors
<class 'numpy.ndarray'>
<class 'list'>
[[  4   0   0   0   0]
 [  1  29   2   0   2]
 [  0   4 110   5   0]
 [  0   0   4  43   4]
 [  0   0   1   6  35]]
Accuracy =  0.884


In [156]:
def rfc(nf, trh, n_comp=0):
    X = imputer_x_var.fit_transform(x_var.values)    
    if(n_comp>0):
        X = pca_(X,n_comp)
    scaler = StandardScaler()
    scaler.fit(X)
    x = scaler.transform(X)
    y = Y_var(pro1)
    ya = array(y)
    kfold = StratifiedKFold(n_splits=6, shuffle=True, random_state=20)
    a = kfold.split(x, ya)
    cvscores = []
    for t in a:
        n_estimators=32
        max_features=5
        clf = RandomForestClassifier(n_estimators=300, criterion='entropy',max_features=50)
        clf.fit(x[t[0]], ya[t[0]])
        y_pred = clf.predict(x[t[1]])
        scores = clf.score(x[t[1]], ya[t[1]])
        target_names = ['0', '1', '2', '3', '4']
        y_true = ya[t[1]]
        print(confusion_matrix(list(ya[t[1]]), list(y_pred)))
        print(classification_report(y_true, y_pred, target_names=target_names))
        print("acc: %.2f%%" % (scores*100))
        cvscores.append(scores * 100)
        mean_score = np.mean(cvscores)
        print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))
        return mean_score
rfc(77,85)    

[[ 3  0  0  0  0]
 [ 0 21  1  0  0]
 [ 0  2 74  2  1]
 [ 0  0  6 27  2]
 [ 0  0  1  2 25]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       0.91      0.95      0.93        22
           2       0.90      0.94      0.92        79
           3       0.87      0.77      0.82        35
           4       0.89      0.89      0.89        28

    accuracy                           0.90       167
   macro avg       0.92      0.91      0.91       167
weighted avg       0.90      0.90      0.90       167

acc: 89.82%
89.82% (+/- 0.00%)


89.82035928143712

In [158]:
def svm_model(nf, trh, n_comp=0):
    X = imputer_x_var.fit_transform(x_var.values)    
    if(n_comp>0):
        X = pca_(X,n_comp)
    scaler = StandardScaler()
    scaler.fit(X)
    x = scaler.transform(X)
    y = Y_var(pro1)
    
     # Split data into training and test set
    x_train, x_dev, y_train, y_dev = train_test_split(x, y, stratify=y,test_size = 0.20, random_state= 20)
     
    print('SVC')
    C = 100000000
    g = 0.0000001
    clf = svm.SVC(kernel='sigmoid', C=C, verbose=0, gamma=g, coef0=0.001)
    print(f"C = {C} and gamma = {g}")
    clf.fit(x_train, y_train)
    score = clf.score(x_dev, y_dev)
    y_pred = clf.predict(x_dev)
    target_names = ['0', '1', '2', '3', '4']
    y_true = y_dev
    print(confusion_matrix(y_true, y_pred))
    print(classification_report(y_true, y_pred, target_names=target_names))
    print("Accuracy = ", score)
    return score

s = svm_model(70,60)


SVC
C = 100000000 and gamma = 1e-07
[[ 3  0  0  0  0]
 [ 3 16  6  0  2]
 [ 0  7 78  7  3]
 [ 0  0 17 24  0]
 [ 0  0  4  4 26]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         3
           1       0.70      0.59      0.64        27
           2       0.74      0.82      0.78        95
           3       0.69      0.59      0.63        41
           4       0.84      0.76      0.80        34

    accuracy                           0.73       200
   macro avg       0.69      0.75      0.70       200
weighted avg       0.74      0.73      0.73       200

Accuracy =  0.735
